# Generated by Django 5.2 on 2025-04-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_address_client_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('client', 'program')},
        ),
    ]
